### ISSUE TITLE
Unit Testing - DEV branch

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#992]
@damirius 
Damir,
I am going to put merge conflicts here.  I am testing the DEV branch of FieldWorkAssistantMVC.  Let me know if I should test another branch.

 * I tried editing a project and I got this:

![screen shot 2015-05-20 at 9 01 11 am](https://cloud.githubusercontent.com/assets/8228624/7730429/2a807bac-fecf-11e4-9b4e-82c418617a29.png)

 * There are a number of broken links.  Few of the left menu items work.

I also tried testing the FieldWorkManagerMVC repository.  So, that can be done, but it has all the same conflicts.

**Comment by damirius** [comment]
@bsaiken

This should be fixed. There were some buttons added to the facility form but no keys were set in project resource file.

**Comment by bsaiken** [comment]
@damirius 
There are still some conflicts.  

Client info is not saved.
![screen shot 2015-05-21 at 7 41 20 am](https://cloud.githubusercontent.com/assets/8228624/7751073/e043a5aa-ff8c-11e4-9ba7-f69521800ec6.png)

The mapping changes have not been merged to the DEV branch.  I still see sidebar menu icons.
![screen shot 2015-05-21 at 7 44 03 am](https://cloud.githubusercontent.com/assets/8228624/7751140/4aaeb8bc-ff8d-11e4-8076-3464c04175fb.png)


Out of curiosity, what buttons got added?

**Comment by damirius** [comment]
@bsaiken

Please do a pull, I recently  merged new set of commits from feature_damir to dev branch.
Some facility buttons, add/remove/edit. I don't know where they are used, they are probably hidden since we only use save/copy buttons which are used across all 3 forms.

I'll check out what's wrong with client save.

**Comment by damirius** [comment]
@bsaiken

That part with client is that method for editing client user entry if you remember. Jeremie worked on it I think and left that for me to finish. I modified that call since it was broken and it should work on the current version of the dev branch. Tell me if you are experiencing same problem after you do a pull.
In any case I should finish that method so it properly edits the user credentials (login/email) for the client. Is there any open issue for that part so you can assign me to it?

**Comment by bsaiken** [comment]
@damirius 
We don't have a Issue for updating the client Issue yet.  We are so short on time, if it is quicker to skip this for now, then skip it (without the broken link).  Having Client users isn't essential just yet.

**Comment by bsaiken** [comment]
@damirius 
I have started testing the dev branch.  I am getting a bug uploading photos - both for Technicians and Locations.  The Photo is saved to the uploads/location and uploads/technician directories.  The `document` table is being populated.  But when the page refreshes the document location is undefined, see attached:
![screen shot 2015-05-22 at 2 33 26 pm](https://cloud.githubusercontent.com/assets/8228624/7780095/a7fcb5fc-008f-11e5-9e8d-dc9b80a3d9e3.png)

**Comment by bsaiken** [comment]
@damirius @gsouvik 
I tried inserting a field analyte from the common field analytes list, and I get an error.  I can type in a field analyte name (even the exact same name as the common field analyte) and it works.

![screen shot 2015-05-22 at 2 59 17 pm](https://cloud.githubusercontent.com/assets/8228624/7780395/383055ae-0093-11e5-9f54-c49da60a44bd.png)

It works fine  using common lab analytes.

**Comment by bsaiken** [comment]
@damirius 
Services is missing from the left menu.

**Comment by bsaiken** [comment]
@damirius 
I modified the left menu so that Service Providers now appears, but adding a SP does not create a new user and I get an error if I try to login with one of the existing SP users in the database.

**Comment by bsaiken** [comment]
@damirius 
I think for the mobile user we just need the communications and edit user modules.  Also, we need the list of forms from the `Collect Data` link in the info window.

**Comment by damirius** [comment]
@bsaiken

I've fixed that issue with photos, as far as SPs go, on my local dev branch which is the same as remote one SP user entries are added properly. Only thing is that they are set to role 4 which is visitor instead of 6. Also we don't have special UI for them except discussions page which can be accessed directly through the link.

**Comment by bsaiken** [comment]
@damirius 
Can you change the redirect for the admin UI "switch" function so it logs in as a SP? This way I can at least get access to one SP and test the communication page.

**Comment by damirius** [comment]
@bsaiken

We changed the flow for them. We should send them the email notification about new message with the link which contains username and encrypted pass in it together with discussion id and we fetch discussion like that. Redirecting him on that page without those variables in the url query will not work. I'll see if I can maybe implement some default discussion loading.

**Comment by bsaiken** [comment]
@damirius 
Yes, I do remember.  We have not implemented this email feature with the link.  I'm just wondering if you thought you had time.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik @damirius 

I have performed the merges from the feature branches to the dev and then from dev branch to feature branches.
